adminer:
    path: /adminer
    controller: App\Controller\AdminerController::index

# Routes for Home

app_home:
    path: /
    controller: App\Controller\HomeController::index
    methods: [GET]

# Routes for ConsoleController
app_console_index:
    path: /console
    controller: App\Controller\ConsoleController::index
    methods: [GET]

app_console_new:
    path: /console/new
    controller: App\Controller\ConsoleController::new
    methods: [GET, POST]

app_console_edit:
    path: /console/{id}/edit
    controller: App\Controller\ConsoleController::edit
    methods: [GET, POST]

app_console_show:
    path: /console/{id}
    controller: App\Controller\ConsoleController::show
    methods: [GET]

app_console_delete:
    path: /console/{id}
    controller: App\Controller\ConsoleController::delete
    methods: [POST]

# Routes for VideoGamesController
app_video_games_index:
    path: /video_games
    controller: App\Controller\VideoGamesController::index
    methods: [GET]

app_video_games_new:
    path: /video_games/new
    controller: App\Controller\VideoGamesController::new
    methods: [GET, POST]

app_video_games_edit:
    path: /video_games/{id}/edit
    controller: App\Controller\VideoGamesController::edit
    methods: [GET, POST]

app_video_games_show:
    path: /video_games/{id}
    controller: App\Controller\VideoGamesController::show
    methods: [GET]

app_video_games_delete:
    path: /video_games/{id}
    controller: App\Controller\VideoGamesController::delete
    methods: [POST]